<?php


$productions = [
	new Movie("Five Nights at Freddy's", "Una guardia giurata problematica inizia a lavorare da Freddy Fazbear's Pizza. Mentre trascorre la sua prima notte di lavoro, si rende conto che il turno di notte da Freddy non sarà così facile da superare.", ['horror'], 5, new Media('five_nights_at_freddys.jpg', "Five Nights at Freddy's"), '2023', '1h 50mins'),

	new TvSerie("L'attacco dei giganti", "Diverse centinaia di anni fa, la razza umana fu quasi sterminata dai giganti. Si racconta di quanto questi fossero alti, privi di intelligenza e affamati di carne umana; peggio ancora, essi sembra divorassero umani più per piacere che per necessario sostentamento. Una piccola percentuale dell'umanità però sopravvisse asserragliandosi in una città circondata da mura estremamente alte, anche più alte del più grande di giganti. Eren è un adolescente che vive in questa città, dove non si vede un gigante da oltre un secolo. Ma presto un orrore indicibile si palesa alle sue porte, ed un gigante più grande di quanto si sia mai sentito narrare, appare dal nulla abbattendo le mura ed imperversando assieme ad altri suoi simili fra la popolazione. Eren, vinto il terrore iniziale, si ripromette di eliminare ogni singolo gigante, per vendicare l'umanità tutta.", ['horror'], 5, new Media('attacco_dei_giganti.jpg', "L'attacco dei giganti"), '2013', '2023', 88, 4),

	new TvSerie("Loki", 'Il volubile cattivo Loki riprende il suo ruolo di Dio del male in seguito agli eventi di "Avengers: Endgame".', ['horror'], 5, new Media('loki.jpg', "Loki"), '2021', '2023', 10, 2),

	new Movie ("Assassinio a Venezia", "Ora in pensione, ritiratosi in un esilio auto-imposto nella città più glamour del mondo, Poirot partecipa controvoglia a una seduta in un palazzo decadente e infestato. Quando uno degli ospiti viene ucciso, il detective si ritrova in un mondo di ombre e segreti.", ['suspense'], 4, new Media('assasinio_a_venezia.jpg', "Assassinio a Venezia"), '2023', '1h 47m'),

	new TvSerie("Gen V", "Nell'unico college americano per supereroi, gli studenti dotati mettono alla prova i loro limiti morali, gareggiando per il primo posto nell'università e per avere la possibilità di unirsi ai Seven, la squadra d'élite di supereroi della Vought International. Quando gli oscuri segreti della scuola vengono alla luce, devono decidere che tipo di eroi vogliono diventare.", ['horror'], 5, new Media('gen_v.jpg', "Gen V"), '2023', '2023', 8, 1),

	new Movie ("Mission Impossible - Dead Reckoning - Parte uno", "Ethan Hunt e la sua squadra dell'IMF si trovano di fronte alla sfida più pericolosa che abbiano mai affrontato: trovare e disinnescare una nuova terrificante arma che minaccia l’ intera umanità. Con il destino del mondo e il controllo del futuro appesi a un filo, la squadra inizierà una frenetica missione in tutto il mondo, per impedire che l’arma cada nelle mani sbagliate. Messo di fronte a un nemico misterioso e onnipotente, tormentato da forze oscure del passato, Ethan sarà costretto a decidere se sacrificare tutto per questa missione, comprese le vite di coloro che gli stanno più a cuore.", ['azione'], 4, new Media('mission_impossible_dead_reckoning_pt1.jpg', "Mission Impossible - Dead Reckoning - Parte uno"), '2023', '2h 43m'),

	new TvSerie("Tutta la luce che non vediamo", 'Le strade di una ragazza francese cieca e di un soldato tedesco si incrociano alla fine della Seconda guerra mondiale.', ['horror'], 4, new Media('tutta_la_luce_che_non_vediamo.jpg', "Tutta la luce che non vediamo"), '2023', '2023', 4, 1),

	new Movie ("Saw X", "Nel film, ambientato nell'arco temporale che unisce SAW I e SAW II, John, malato e disperato, si reca in Messico per sottoporsi a una rischiosa procedura medica sperimentale nella speranza di una cura miracolosa per il suo cancro. Il suo sogno svanisce quando scopre che l’intera operazione non è altro che una truffa per frodare i più vulnerabili. Con un nuovo scopo, vendicarsi dei suoi truffatori, il famigerato serial killer torna al suo lavoro con il suo subdolo e inconfondibile stile.", ['suspense'], 4, new Media('saw_x.jpg', "Saw X"), '2023', '1h 58m')
];